### ISSUE TITLE
InCarPC Specification

### ISSUE THREAD

**Issue by SeanWilliams-Teesside** [FS-AI/FS-AI_Compute#5]
Hi Ian,

FS-AI ADS-DV AI Base Computer is listed as InCarPC CQ67G. We are aware InCarPC have new model CQ77G - faster processor, which I believe other competition teams have procured. Looking ahead I expect future support for CQ67G to be limited. Can you offer any advise which model a team just starting out in FS should be looking to invest.

Thanks

**Comment by ianrmurphy** [comment]
Hi Sean,

At competition you will need to provide a bootable SSD compatible with the CQ67G. It has been noted that key to a successful boot is BIOS settings compatibility, and key to a successful software launch is IO compatibility, especially naming of e.g. USB ports and Ethernet / Wifi ports.

Assuming the CQ77G uses a similar motherboard and BIOS to the CQ67G this should be straightforward to verify and adapt if needed. However if you are using the GPU for compute, you should verify that the GPU models and / or software environment are compatible. If the CQ77G has a newer GPU you may need to downgrade your SDK to work on the CQ67G.

The CAN IO used in the ADS-DV CQ67G units is manufactured by PEAK Systems Gmbh. and it is highly recommended that you specify this CAN IO manufacturer. Only PEAK Systems CAN IO has been tested as part of the ADS_DV commissioning process, and this is the only CAN IO tested to work with the FS-AI_API.

Physical compatibility is also useful but not essential, it depends where you plan to use the computer. Also, it depends what OS you plan to use. All development work has been conducted on Ubuntu 20.04 Linux, which also has the advantage of supporting UEFI boot.

Some resources on preparing an SSD for booting on the CQ67G will be released. An SSD prepared on an Intel NUC and a Dell laptop have been known to boot OK, but required renaming of Ethernet & Wifi adapter settings due to motherboard differences.

Thanks, Ian

**Comment by SeanWilliams-Teesside** [comment]
Hi Ian,

Thanks for your prompt and comprehensive reply, all very useful information. In many respects investing in the same model installed to the DV (CQ67G) makes sense, and most likely will be the our first choice. For your info the following spec was lifted from the InCarPC webpage, the chap I spoke to indicated this was compatible with the spec listed on the FS GitHub pages.

CPU: Intel Core i7-4650U up to 3.3 GHz (£1140.00)
RAM: 8 GB RAM (£65.00)
Primary Hard Drive/SSD: 120 GB Value Standard Temperature SSD (£45.00)
Mini PCIe 1: GPS (£67.00)
Mini PCIe 2: 2-channel CAN-bus Standard (£102.00)
Mini PCIe 3: Wi-Fi and Bluetooth (£40.00)
Operating System: No operating system licence (£0.00)
Internal back-up battery / 10-muinute UPS (£76.00)

Many thanks,
Sean

**Comment by ianrmurphy** [comment]
Hi,

Note that you will need to explicitly specify the PEAK Systems CAN adapter as the 'Standard' option at £102 is NOT made by PEAK Systems and has driver issues. On the quote for the IMechE CQ67Gs this appears as:

Dual channel galvanically isolated CAN interface (Advanced / PCIe signalling) occupying Mini PCIe slot, including API.

They cost about £150 more each in 2019. For reference the PEAK Part number is IPEH-003049:  https://www.peak-system.com/PCAN-miniPCIe.285.0.html?&L=1

Thanks, Ian
